name: Build & Deploy
on:
  push: { branches: [main] }
  schedule: [ { cron: "0 22 1 * *" } ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - run: pnpm i
      - run: pnpm exec ts-node scripts/updatePublications.ts || true
      - run: pnpm export
      - run: touch out/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
